# Generated by Django 4.2.9 on 2024-01-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
