# Generated by Django 4.2.9 on 2024-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='velayat',
            field=models.CharField(default='Rahman', max_length=15),
            preserve_default=False,
        ),
    ]
