# Generated by Django 4.2.9 on 2024-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_billingaddress_zip_code_billingaddress_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
