# Generated by Django 4.2.9 on 2024-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_billingaddress_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='velayat',
            field=models.CharField(choices=[('A', 'Ahal'), ('M', 'Mary'), ('B', 'Balkan'), ('D', 'Dashoguz'), ('L', 'Lebap')], default='M', max_length=15),
        ),
    ]
